[project]
name = "spotlight-tools"
version = "0.2.0"
description = ""
authors = [
    {name = "Sibo Wang-Chen", email = "sibo.wang@epfl.ch"}
]
readme = "README.md"
requires-python = ">=3.12,<3.14"
dependencies = [
    "opencv-python (>=4.11,<5.0)",
    "svgwrite (==1.4.3)",
    "numpy (>=2.0,<3.0)",
    "tqdm (>=4.67,<5.0)",
    "ipython (>=9.0,<10.0)",
    "ipykernel (>=6.29,<7.0)",
    "matplotlib (>=3.10,<4.0)",
    "joblib (>=1.5,<2.0)",
    "pandas (>=2.2,<3.0)",
    "scipy (>=1.15,<2.0)",
    "pytest (>=8.3,<9.0)",
    "scikit-learn (>=1.6,<2.0)",
    "seaborn (==0.13.2)",
    "ipywidgets (>=8.1,<9.0)",
    "pyyaml (>=6.0,<7.0)",
    "tyro (>=1.0,<2.0)",
    "vidgear (==0.3.4)",
    "setuptools (>=78,<79)",  # needed for vidgear
    "cmasher (>=1.9,<2.0)",
    "sleap (==1.5.*)",
    "sleap-nn (==0.0.3)",
]

[tool.poetry]
packages = [{include = "spotlight_tools", from = "src"}]
include = ["src/spotlight_tools/assets/**"]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
generate-calibration-board = "spotlight_tools.scripts.generate_board:main"
fit-calibration-model = "spotlight_tools.scripts.fit_calibration:main"
postprocess-recording = "spotlight_tools.scripts.postprocess_recording:main"
visualize-stage-trajectory = "spotlight_tools.scripts.visualize_stage_trajectory:main"
